accounts/urls.py
from django.urls import path, reverse_lazy
from . import views
from django.contrib.auth import views as auth_view

app_name = 'accounts'

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('signup/', views.user_signup, name='signup'),
    path('logout/', views.user_logout, name='logout'),
    path(
        "password_change/", auth_view.PasswordChangeView.as_view(
            success_url=reverse_lazy("accounts:password_change_done")
        ), name="password_change"
    ),
    path(
        "password_change/done/",
        auth_view.PasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    path("password_reset/", auth_view.PasswordResetView.as_view(
        success_url=reverse_lazy("accounts:password_reset_done")
    ), name="password_reset"),
    path(
        "password_reset/done/",
        auth_view.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_view.PasswordResetConfirmView.as_view(
            success_url=reverse_lazy("accounts:password_reset_complete")
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_view.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
]

books/urls.py
from django.urls import path
from . import views

app_name = "books"

urlpatterns = [
    path('', views.book_list, name="book_list"),
    path('book/<int:pk>', views.book_detail, name="book_detail"),
    path('book/add', views.add_book, name='add_book'),
    path('author/add', views.add_author, name='add_author'),
    path('book/edit/<int:pk>', views.edit_book, name='edit_book'),
    path('book/delete/<int:pk>', views.delete_book, name='delete_book'),
    path('my-books/', views.my_books, name='my_books'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('books.urls')),
    path('user/', include('accounts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

books/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class Author(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Book(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    author = models.ForeignKey(Author, on_delete=models.CASCADE, related_name="books")
    published_at = models.DateField(default=timezone.now)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignupForm(UserCreationForm):
    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control'})
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control'})
    )

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'password1': forms.PasswordInput(attrs={'class': 'form-control'}),
            'password2': forms.PasswordInput(attrs={'class': 'form-control'}),
        }

    def __init__(self, *args, **kwargs):
        super(SignupForm, self).__init__(*args, **kwargs)
        for field_name in self.fields:
            self.fields[field_name].help_text = None


class LoginForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control'})
    )

books/forms.py
from django import forms
from .models import Author, Book


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ('title', 'description', 'published_at', 'author')
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
            'author': forms.Select(attrs={'class': 'form-control'}),
            'published_at': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'created_by': forms.HiddenInput(),
        }

    author = forms.ModelChoiceField(queryset=Author.objects.all(), widget=forms.Select(attrs={'class': 'form-control'}))


class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = ('name', )
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'})
        }

accounts/views.py
from django.shortcuts import render, redirect

from .forms import SignupForm, LoginForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages


def user_signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('accounts:login')
        else:
            messages.error(request, 'Invalid form data.')
            return redirect('accounts:signup')
    form = SignupForm()
    return render(request, 'accounts/signup.html', {'form': form})


def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            user_2 = authenticate(request, email=username, password=password)
            if user or user_2:
                login(request, user)
                return redirect('books:book_list')
            else:
                messages.error(request, 'Invalid username or password.')
                return redirect('accounts:login')
        else:
            messages.error(request, 'Invalid form data.')
            return redirect('accounts:login')
    form = LoginForm()
    return render(request, 'accounts/login.html', {'form': form})


def user_logout(request):
    logout(request)
    messages.success(request, 'Successfully logged out.')
    return redirect('accounts:login')

books/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Book
from .forms import BookForm, AuthorForm
from django.contrib.auth.decorators import login_required


@login_required
def book_list(request):
    books = Book.objects.all()
    return render(request, 'books/book_list.html', {"books": books})


@login_required
def book_detail(request, pk):
    book = get_object_or_404(Book, pk=pk)
    previous_page = request.GET.get('from', None)
    return render(request, 'books/book_detail.html', {"book": book, 'previous_page': previous_page})


@login_required
def add_book(request):
    if request.method == "POST":
        form = BookForm(request.POST)
        if form.is_valid():
            book = form.save(commit=False)
            book.created_by = request.user
            book.save()
            return redirect('books:book_list')
    form = BookForm()
    return render(request, 'books/book_form.html', {'form': form})


@login_required
def add_author(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('books:add_form')
    form = AuthorForm()
    return render(request, 'books/author_form.html', {'form': form})


def edit_book(request, pk):
    book = get_object_or_404(Book, pk=pk, created_by=request.user)
    if request.method == 'POST':
        form = BookForm(request.POST, instance=book)
        if form.is_valid():
            form.save()
            return redirect('books:book_detail', pk=book.pk)
    form = BookForm(instance=book)
    return render(request, 'books/book_form.html', {'form': form, 'book': book})


@login_required
def delete_book(request, pk):
    book = get_object_or_404(Book, pk=pk, created_by=request.user)
    if request.method == 'POST':
        book.delete()
        return redirect('books:book_list')

    return render(request, 'books/confirm_form.html', {'book': book})


@login_required
def my_books(request):
    books = Book.objects.filter(created_by=request.user)
    return render(request, 'books/my_books.html', {'books': books, 'my_book': True})

templates/accounts/login.html
{% extends "accounts/user.html" %}

{% block title %}Login{% endblock %}

{% block content %}
<h1>Login</h1>
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li class="{{ message.tags }}">{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}
<form action="{% url 'accounts:login' %}" method="post">
    {% csrf_token %}
    <div class="form-group">
        <label for="id_username">Username:</label>
        {{ form.username }}
    </div>
    <div class="form-group">
        <label for="id_password">Password:</label>
        {{ form.password }}
    </div>
    <button type="submit">Login</button>
    <a href="{% url 'accounts:signup' %}">Don't have an account?</a>
    <a href="{% url 'accounts:password_reset' %}">Forgot password?</a>
</form>
{% endblock %}

templates/accounts/signup.html
{% extends "accounts/user.html" %}

{% block title %}Signup{% endblock %}

{% block content %}
<h1>Signup</h1>
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li class="{{ message.tags }}">{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}
<form action="{% url 'accounts:signup' %}" method="post">
    {% csrf_token %}
    <div class="form-group">
        <label for="id_username">Username:</label>
        {{ form.username }}
    </div>
    <div class="form-group">
        <label for="id_email">Email:</label>
        {{ form.email }}
    </div>
    <div class="form-group">
        <label for="id_password1">Password:</label>
        {{ form.password1 }}
    </div>
    <div class="form-group">
        <label for="id_password2">Password confirmation:</label>
        {{ form.password2 }}
    </div>
    <button type="submit">Signup</button>
    <a href="{% url 'accounts:login' %}">Already have an account?</a>
</form>
{% endblock %}

templates/accounts/user.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/accounts.css' %}">
</head>
<body>
    <div class="auth-container">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Library{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/books.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
    {% block header %}{% endblock %}
    <div class="container">
        {% block body %}{% endblock %}
    </div>

    <footer>
        <p>Powered by <a href="https://www.linkedin.com/in/abdulla-dev/">Abdulla Abdukulov</a></p>
    </footer>

    <script type="text/javascript" src="{% static 'js/scripts.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

templates/books/author_form.html
{% extends 'base.html' %}

{% block title %}Add Author{% endblock %}

{% block body %}
    <h1>Add Author</h1>
    <form action="{% url 'books:add_author' %}" method="post" onsubmit="setTimeout(closePopup, 10);">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
{% endblock %}

templates/books/book_detail.html
{% extends 'base.html' %}

{% block title %}{{ book.title }}{% endblock %}

{% block body %}
    <h1>{{ book.title }}</h1>
    <p>{{ book.description }}</p>
    <p><strong>Author:</strong> {{ book.author.name }}</p>
    <p><strong>Publication Date:</strong> {{ book.published_at }}</p>
    {% if previous_page == 'book_list' %}
        <a href="{% url 'books:book_list' %}" class="back-link">Back to Book List</a>
    {% elif previous_page == 'my_books' %}
        <a href="{% url 'books:my_books' %}" class="back-link">Back to My Books</a>
    {% else %}
        <a href="{% url 'books:book_list' %}" class="back-link">Back to Book List</a>
    {% endif %}
{% endblock %}

templates/books/book_form.html
{% extends 'base.html' %}

{% block title %}{% if book %} Edit Book {% else %}Add book {% endif %}{% endblock %}

{% block body %}
    <h1>{% if book %} Edit Book {% else %} Add book {% endif %}</h1>
    <form action="{% if book %} {% url 'books:edit_book' pk=book.pk %} {% else %} {% url 'books:add_book' %} {% endif %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="add-author-link">
            <a href="{% url 'books:add_author' %}" onclick="openPopup(this.href); return false;">Add new author</a>
        </div>
        <button type="submit">Submit</button>
    </form>
{% endblock %}

templates/books/book_list.html
{% extends 'base.html' %}

{% block title %}Library{% endblock %}

{% block header %}{% include 'header.html' %}{% endblock %}

{% block body %}
    <a href="{% url 'books:add_book' %}" class="add-book">Add Book</a>
    <ol>
        {% for book in books %}
            <li class="book-list">
                <div class="book-title"><a href="{% url 'books:book_detail' pk=book.pk %}?from=book_list">{{ book.title }}</a></div>
                <span class="created-by">Created by: {{ book.created_by.username }}</span>
            </li>
        {% endfor %}
    </ol>
{% endblock %}

templates/books/confirm_form.html
{% extends 'base.html' %}

{% block title %}Are you sure?{% endblock %}

{% block body %}
    <h1>Are you sure you want to delete "{{ book.title }}"?</h1>
    <div class="btn-container">
        <form action="{% url 'books:delete_book' pk=book.pk %}" method="post">
            {% csrf_token %}
            <button class="btn-yes" type="submit">Yes, I'm sure</button>
        </form>
        <form action="{% url 'books:book_list' %}">
            <button class="btn-no">No, take me back</button>
        </form>
    </div>
{% endblock %}

templates/books/my_books.html
{% extends 'base.html' %}

{% block title %}My books{% endblock %}
{% block header %}{% include 'header.html' %}{% endblock %}
{% block body %}
    <a href="{% url 'books:add_book' %}" class="add-book">Add Book</a>
    <ol>
        {% for book in books %}
            <li class="book-list">
                <div class="book-title"><a href="{% url 'books:book_detail' pk=book.pk %}?from=my_books">{{ book.title }}</a></div>
                <span class="created-by">Created by: {{ book.created_by.username }}</span>
                <div class="book-details">
                    <span class="book-actions">
                        <a href="{% url 'books:edit_book' pk=book.pk %}">Update</a>
                        <a href="{% url 'books:delete_book' pk=book.pk %}">Delete</a>
                    </span>
                </div>
            </li>
        {% endfor %}
    </ol>
{% endblock %}

templates/header.html
<nav class="navbar navbar-expand-lg navbar-dark">
    <div class="container">
        {% if request.path == '/my-books/' %}
            <a class="navbar-brand" href="{% url 'books:my_books' %}">My Books</a>
        {% else %}
            <a class="navbar-brand" href="/">Welcome, {{ user.username }}</a>
        {% endif %}
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="/">Home</a>
            </li>
            <li class="nav-item {% if request.path == '/my-books/' %}active{% endif %}">
                <a class="nav-link" href="{% url 'books:my_books' %}">My books</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
            </li>
        </ul>
    </div>
</nav>